### ISSUE TITLE
Reorganise files

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/illustrations#1]
In order to keep the links in this repository usable for longer we should try iterating more than updating and organising all of our files in this repo effectively.

Rename the files and folder so they are easier to use.

**Comment by ElenaFdR** [comment]
Here's a proposal.

This repo would contain:

- readme (with links to issues for future illustration ideas, the illustrations index)
- licence
- authors
- illustrations folder
  - index (with overview of illustrations and links to metadata pages)
  - illustration.svg file
  - metadata page for each illustration.svg file

**Comment by ElenaFdR** [comment]
I've [started a spreadsheet](https://docs.google.com/spreadsheets/d/1o5BJl6aEhGb3nx09C-W1aPu29mBAYwbcnF0kMqiwgi8/edit?usp=sharing) to collect/collate metadata.

**Comment by fdeerenberg** [comment]
Cool!

**Comment by ElenaFdR** [comment]
This is pretty cool: http://illustrations.publiccode.net/

**Comment by ElenaFdR** [comment]
I've merged a first version of this, so I'm going to close this issue.

**Comment by ElenaFdR** [comment]
Unless you think the specific files also still need better names, @bvhme?
