### ISSUE TITLE
New illustration: members

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/illustrations#4]

**Comment by lscheske** [comment]
Hey @fdeerenberg & @ElenaFdR , I had an idea for how we could represent our member ecosystem. We could have an illustration that has some of our recurring design elements such as:

* Foundation Logo
* The hexagon
* Connecting fine lines

Some of the things that would be great for it to represent is: 
* a decentralized network
* different types of public organizations

All using Floris' amazing style!

I've tried to make a mockup:

![Photo on 10-08-2020 at 11 38](https://user-images.githubusercontent.com/61967157/89769773-0776dc80-dafe-11ea-81fc-772e76da9191.jpg)

**Comment by lscheske** [comment]
Yes, I'd like to revisit the illustration based on my comment on this issue.

**Comment by fdeerenberg** [comment]
@lscheske I think there has been a miscommunication. I did not start work on this issue yet. The illustrations that I made we're about membership, but not prior to this issue you created. So let's pick this up soon!

**Comment by lscheske** [comment]
> @lscheske I think there has been a miscommunication. I did not start work on this issue yet. The illustrations that I made we're about membership, but prior to this issue you created. So let's pick this up soon!

Cool, thanks! I was confused because it was moved to "done" in the project pipeline. Happy to pick it up soon !

**Comment by fdeerenberg** [comment]
Hi @lscheske @nebster @ElenaFdR Here's the first iteration. I (ofcourse) like the one with the peache background the best. I would also love to animate that one (seeing the lines transfer data, maybe adding a new member?).

let me know what you guys think!
![membership interconnectivity-1](https://user-images.githubusercontent.com/13848073/97695598-99123c80-1aa4-11eb-9be2-acd6fe2ed81d.png)
![membership interconnectivity-2](https://user-images.githubusercontent.com/13848073/97695605-9b749680-1aa4-11eb-8670-a5ce64ba65ca.png)
![membership interconnectivity-3](https://user-images.githubusercontent.com/13848073/97695608-9ca5c380-1aa4-11eb-8848-eca1eb400487.png)
![membership interconnectivity-4](https://user-images.githubusercontent.com/13848073/97695611-9d3e5a00-1aa4-11eb-8b56-f1834afa0bdc.png)
![membership interconnectivity](https://user-images.githubusercontent.com/13848073/97695615-9dd6f080-1aa4-11eb-90e2-9312f8a59cfc.png)

**Comment by lscheske** [comment]
I really like 1) 2) 4). I think the symmetry looks professional, the hexagon is used well, and I clearly see the network aspect.

Animations would be really cool! (I assume the little arrows on the lines will be moving?) Looking forward to that

**Comment by fdeerenberg** [comment]
![Foundation members animation](https://user-images.githubusercontent.com/13848073/103760395-55443200-5015-11eb-8540-9d8183640f54.gif)
@lscheske

**Comment by lscheske** [comment]
This looks great, Floris! I again have not a very strong positive feeling towards the peach background. It is very hip, but I don't see it fitting in with our comms at the moment. It's a new color that has not been part of our palette before. It may be difficult to match when we want to use it across web/publications etc. I think we should stick to the blue background, or even a white one.

Are the previous illustrations (1, 2, 4) finalized and ready for use?

**Comment by fdeerenberg** [comment]
![members_purple](https://user-images.githubusercontent.com/13848073/106718920-f963cd80-6601-11eb-9cb9-b13dcdee139b.gif)

Yes, I'll upload them to the repo
