### ISSUE TITLE
Ecosystem diagram / infographic

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/illustrations#5]
I would love to have an stylized illustration which shows a view of a "typical" open source project. Something like the illustration below but may be generalize it a bit more. I would like to have this illustration as a "talking picture" to explain to vendors as well as municipalities what the different roles in a ecosystem are, to explain that working on a share codebase does not mean they can't innovate or customize based on their own needs and requirements and also explain what the role of a codebase steward would be.

![governance-models](https://user-images.githubusercontent.com/16088854/86582521-0a703180-bf82-11ea-8fe7-87846596d979.png)

**Comment by fdeerenberg** [comment]
Great idea, but I would need your help to generalize it - because I don't know that much (yet) about the inner workings of these things. Again an issue for @ElenaFdR to prioritize

**Comment by felixfaassen** [comment]
Hi @fdeerenberg thanks so much for your beautiful design. I really like it. See below a few remarks or thoughts I had when looking at it, just my 2 cents ;-)

- Dark background makes it a bit hard to read and also harder to incorporate in our minimalist / white space design language. Also when printing you need a lot of ink so I would opt for a whit background or a lighter themed design
 
- I like the 3D perspective but a square 3d perspective in combination with the dark theme make it hard to make a visual relation between the smaller blocks with texts and the large square visualising the ecosystem itself.

- Maybe a spheroid or sphere/solar theme as analogy could provide a solution for the above issue I mentioned. Of course I'm no designer ;-) so probably better ways.  

- Maybe a legend for the different colours would be nice or indicating (re itterating) what the colours mean in the ecosystem so orange=users, green= contributors etc. and small description what a user, end-user and contributor is.

Really love it! Looking forward to your thoughts on this.

**Comment by felixfaassen** [comment]
@AlbaRoza  @Ainali @ericherman @clausmullie could you also have a look at the new illustration for the codebase ecosystem and provide @fdeerenberg with comments and feedback?

**Comment by Ainali** [comment]
I like it a lot! 
* As for the dark background, I don't mind it at all. We will probably not print it a lot, but mostly use it in digital form any way. Also, all of our illustrations are colour rich, it's only things without illustrations that are minimalistic.
* I don't understand what you mean with 3D @felixfaassen, to me this looks like a flat design (ie. it is not a cube in isometric perspective, it's a hexagon).
* I also noticed some errors in my original sketch, the bottom left market hexagon should be a vendor.
* There are some small typos, it should be "backend" and "municipalities"

**Comment by fdeerenberg** [comment]
Thank you for your feedback guys! I agree with the dark background, So I will make a light one and a dark one to serve both situations. But first I added the coordinator parts and changed the hexagons to a more circular shape. This way it's readability increases. fixed typos as well
![Ecosystem diagram v2](https://user-images.githubusercontent.com/13848073/94556059-cd53cc80-025c-11eb-8e4a-0304c5a7cbce.png)

**Comment by felixfaassen** [comment]
@fdeerenberg sorry for the late feedback. I like that you created a white version. Would be cool to use the same shapes as you have in the darker version. Apart from a matter in taste I think it would be nice that both illustration have the exact same style in a dark and a light version. So applying the style of the dark version to the light version would be very nice.

**Comment by Ainali** [comment]
Hmm, I don't remember if there was a significance to the three lines in "one company full service" compare to the no lines used in "backend as a service", but the Vendor should cross one more circle inwards in the former. I remember turning that ring 90 degrees  to reach that far intentionally.

**Comment by AlbaRoza** [comment]
I also prefer the white background one, I find it easier to read and therefore more likely to be used in an explanation to third parties outside the Foundation.

@Ainali I think what @felixfaassen tries to say when he means "minimalistic" is something a little less colorful, perhaps?

However, as @felixfaassen pointed out, I would also like to have the dark version of this last one if possible.

Thanks, @fdeerenberg!

**Comment by fdeerenberg** [comment]
@Ainali @felixfaassen @AlbaRoza Thanx for the feedback guys! here's the new white background iteration.
![Ecosystem diagram v1](https://user-images.githubusercontent.com/13848073/97693277-3bc8bc00-1aa1-11eb-97bc-1e75bb22aa4d.png)

**Comment by Ainali** [comment]
Nice! Here's a thing I am not entirely sure of, but that I noticed now. In three out of the four examples, the government part is orange, but in the do it yourself it is yellow. Should that one be orange instead to signal it is a government type?

**Comment by ElenaFdR** [comment]
I'm going to close this now, since there's been no movement on it in months.
